FROM ubuntu:24.04

RUN apt-get update && apt-get install -y g++ make && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY src ./src

RUN g++ -pthread src/server.cc -o server \
    && g++ -pthread src/client.cc -o client

CMD ["bash"]
